name: flutter_login_screen
description: Functional Flutter Starter Kit
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  shared_preferences: ^2.0.6
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  cloud_firestore: ^2.2.1
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  flutter_facebook_auth: ^3.4.1
  http: ^0.13.3
  image_picker: ^0.8.0+3
  firebase_storage: ^8.1.1
  cached_network_image: ^3.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: android/app/src/main/ic_launcher-playstore.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/