name: flutter_login_screen
description: Functional Flutter Starter Kit
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  page_view_indicators: 1.3.1
  shared_preferences: 0.5.6
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  progress_dialog: ^1.2.4
  flutter_facebook_login: 3.0.0
  http: 0.12.2
  image_picker: ^0.6.7+21
  firebase_storage: ^7.0.0
  cached_network_image: ^2.5.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/
